### ISSUE TITLE
Page doesn't exist

### ISSUE THREAD

**Issue by nataliepjlin** [JJuiceCode/hugo.theme.bookworm#1]
Hi! I clone this entire repository. When I use command `hugo server` , the page on localhost says **``doesn't exist**. Is there any way to fix it? Thanks a lot!

**Comment by JJuiceCode** [comment]
Hi nataliepjlin~
Recently, there has been no modification related to '
https://github.com/JJuiceCode/hugo.theme.bookworm'.
 I'm not even sure why such a problem occurs.
Sorry for not being of any help.
Hava a nice day!

2022년 3월 13일 (일) 오후 7:09, nataliepjlin ***@***.***>님이 작성:

**Comment by nataliepjlin** [comment]
@JJuiceCode Got it! Thank you:)
